/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './home.component';
const styles_HomeComponent:any[] = ([] as any[]);
export const RenderType_HomeComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HomeComponent,
  data: {}
}
);
export function View_HomeComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['The Home Page']))
  ]
  ,(null as any),(null as any));
}
function View_HomeComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_HomeComponent_0,RenderType_HomeComponent)),
    import0.ɵdid(49152,(null as any),0,import1.HomeComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HomeComponentNgFactory:import0.ComponentFactory<import1.HomeComponent> = import0.ɵccf('ng-component',import1.HomeComponent,View_HomeComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvbm9kZVRldC9jdXN0b20tcHJvamVjdC9zcmMvYXBwL2hvbWUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL25vZGVUZXQvY3VzdG9tLXByb2plY3Qvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL25vZGVUZXQvY3VzdG9tLXByb2plY3Qvc3JjL2FwcC9ob21lLmNvbXBvbmVudC50cy5Ib21lQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9BZG1pbmlzdHJhdG9yL0RvY3VtZW50cy9ub2RlVGV0L2N1c3RvbS1wcm9qZWN0L3NyYy9hcHAvaG9tZS5jb21wb25lbnQudHMuSG9tZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5UaGUgSG9tZSBQYWdlPC9oMT4iLCI8bmctY29tcG9uZW50PjwvbmctY29tcG9uZW50PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUFJOzs7Ozs7SUNBSjtnQkFBQTs7OzsifQ==
