/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from './users.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './users.component';
const styles_UsersComponent:any[] = [import0.styles];
export const RenderType_UsersComponent:import1.RendererType2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_UsersComponent,
  data: {}
}
);
export function View_UsersComponent_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'h1',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import1.ɵted((null as any),['Users Component here']))
  ]
  ,(null as any),(null as any));
}
function View_UsersComponent_Host_0(l:any):import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    (l()(),import1.ɵeld(0,(null as any),(null as any),1,'ng-component',([] as any[]),(null as any),(null as any),(null as any),View_UsersComponent_0,RenderType_UsersComponent)),
    import1.ɵdid(49152,(null as any),0,import2.UsersComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UsersComponentNgFactory:import1.ComponentFactory<import2.UsersComponent> = import1.ɵccf('ng-component',import2.UsersComponent,View_UsersComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvbm9kZVRldC9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9BZG1pbmlzdHJhdG9yL0RvY3VtZW50cy9ub2RlVGV0L2N1c3RvbS1wcm9qZWN0L3NyYy9hcHAvdXNlcnMvdXNlcnMuY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvbm9kZVRldC9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvbm9kZVRldC9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLmNvbXBvbmVudC50cy5Vc2Vyc0NvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxoMT5Vc2VycyBDb21wb25lbnQgaGVyZTwvaDE+IiwiPG5nLWNvbXBvbmVudD48L25nLWNvbXBvbmVudD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQUk7Ozs7OztJQ0FKO2dCQUFBOzs7OyJ9
