/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './users-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './users.component.ngfactory';
import * as import4 from './users.component';
class UsersRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.UsersRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _UsersRoutingModule_1:import1.UsersRoutingModule;
  _ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.UsersComponentNgFactory],([] as any[]));
  }
  createInternal():import1.UsersRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)),this.parent.get(import2.Router,(null as any)));
    this._UsersRoutingModule_1 = new import1.UsersRoutingModule();
        this._ROUTES_2 = [[{
          path: '',
          component: import4.UsersComponent
        }
    ]];
    return this._UsersRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.UsersRoutingModule)) { return this._UsersRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const UsersRoutingModuleNgFactory:import0.NgModuleFactory<import1.UsersRoutingModule> = new import0.NgModuleFactory<any>(UsersRoutingModuleInjector,import1.UsersRoutingModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQWRtaW5pc3RyYXRvci9Eb2N1bWVudHMvbm9kZVRldC9jdXN0b20tcHJvamVjdC9zcmMvYXBwL3VzZXJzL3VzZXJzLXJvdXRpbmcubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0FkbWluaXN0cmF0b3IvRG9jdW1lbnRzL25vZGVUZXQvY3VzdG9tLXByb2plY3Qvc3JjL2FwcC91c2Vycy91c2Vycy1yb3V0aW5nLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
